# 存取SQLite

**SQLite為檔案型的關聯式資料庫，使用一個檔案當成資料庫，不用安裝資料庫伺服器，就可以練習SQL語法操作資料庫，因為SQLite資料庫的資料存取速度不是很好，當所需儲存的資料不多，就可以使用SQLite資料庫。Python提供模組`sqlite3`實作SQLite資料庫，以下介紹模組`sqlite3`的重要函式。**

**模組`sqlite3`用於管理SQLite資料庫，經由模組`sqlite3`所提供的函式來連線資料庫，進行資料庫的新增、刪除與更新資料。以下介紹模組`sqlite3`的重要函式。**

- **`sqlite3.connect(file)` : 連線檔案file為SQLite資料庫，回傳物件sqlite3.Connection**
- **`sqlite3.Connection.cursor()` : 將物件sqlite3.Connection經由函式cursor，回傳物件sqlite3.Cursor**
- **`sqlite3.Cursor.execute(sql)` : 經由物件sqlite3.Cursor執行SQL語法，管理指定的SQLite資料庫**
- **`sqlite3.Cursor.fetchall()` : 配合sqlite3.Cursor.execute(sql)中的SQL語法所選取的資料，使用函式fetchall()，取出所有資料儲存到串列**
- **`sqlite3.Cursor.close()` : 關閉指定的物件Cursor**

## 使用模組`sqlite3`管理SQLite資料庫

**使用模組`sqlite3`新增資料庫school，新增資料表stu，用於儲存學生學號、姓名、身分證字號與電話，並練習新增一筆資料到資料表stu**

In [2]:
import sqlite3

con = sqlite3.connect('school.db')
cur = con.cursor()

cur.execute("DROP TABLE stu")

cur.execute("""CREATE TABLE stu(
                stuId InTEGER PRIMARY KEY,
                name VARCHAR(50) not null,
                pId VARCHAR(20) not null,
                phone VARCHAR(20) not null)""")

cur.execute("INSERT INTO stu VALUES (104001, 'Claire', 'B342222', '1245667')")

cur.execute("SELECT * FROM stu")

rows = cur.fetchall()
print(rows)
cur.close()

[(104001, 'Claire', 'B342222', '1245667')]


# 使用`SQLAlchemy`與`PyMysql`存取Mysql

**模組`SQLAlchemy`用於連線資料庫，而模組`PyMysql`是模組`SQLAlchemy`連線資料庫時，所指定的Mysql資料庫驅動程式。模組`SQLAlchemy`的重要函式如下:**

- **`sqlalchemy.create_engine(db)` : 利用物件Sqlalchemy的函式`create_engine`，以連線字串db為輸入，連線指定的資料庫，回傳物件Connection**
    - **註:連線字串db格式為`資料庫類型+驅動程式://使用者名稱:密碼@主機名稱[:Mysql的連接渠道]/資料庫名稱`**
- **`sqlalchemy.engine.Connection.execute(sql)` : 利用物件Connection的函式`execute`執行指定的sql，回傳物件ResultProxy**
- **`sqlalchemy.engine.ResultProxy.fetchall()` : 利用物件ResultProxy的函式`fetchall`取出物件ResultProxy的所有資料到串列**

## 使用模組`SQLAlchemy`與`PyMysql`管理Mysql資料庫

**使用模組`SQLAlchemy`與`PyMysql`連線Mysql資料庫，建立資料庫school與資料表stu，插入資料到資料表stu，取出資料表stu的所有資料，最後刪除資料表stu與資料庫school**

In [3]:
import pymysql

try:
    connect_db = pymysql.connect(host="localhost", user="root", password="", 
                                 database="school", charset='utf8' )
    print('連接成功')
    
except pymysql.Error as e:
    print('連接失敗' + str(e))

連接成功


In [4]:
with connect_db.cursor() as cursor:
    cursor.execute('CREATE DATABASE IF NOT EXISTS school')
    cursor.execute('USE school')
    
    sql = """CREATE TABLE stu(
            stuId INTEGER PRIMARY KEY,
            name VARCHAR(50) not null,
            pId VARCHAR(20) not null,
            phone VARCHAR(20) not null)"""
    # 執行 SQL 指令
    cursor.execute(sql)
    
    sql = "INSERT INTO stu VALUES (104001, 'Claire', 'B342222', '1245667')"
    # 執行 SQL 指令
    cursor.execute(sql)
    
    # 取出全部資料
    cursor.execute("SELECT * FROM stu")
    rows = cursor.fetchall()
    for row in rows:
        print(row)

    cursor.execute('DROP TABLE IF EXISTS stu')
    cursor.execute('DROP DATABASE IF EXISTS school')
    
# 關閉 SQL 連線
connect_db.close()

(104001, 'Claire', 'B342222', '1245667')


# 習題

## 查詢學生成績

**使用SQL語法`SELECT FROM WHERE`，結合學生基本資料表與成績表查詢學生成績，學生成績由姓名(name)、學期(sem)、科目(sub)與成績(score)組成**

In [5]:
import pymysql

try:
    connect_db = pymysql.connect(host="localhost", user="root", password="", 
                                 database="practice", charset='utf8' )
    print('連接成功')
    
except pymysql.Error as e:
    print('連接失敗' + str(e))

連接成功


In [6]:
with connect_db.cursor() as cursor:
    # 創建學生資料表
    sql = """CREATE TABLE stu(
            stuId INTEGER PRIMARY KEY,
            name VARCHAR(50) not null,
            pId VARCHAR(20) not null,
            phone VARCHAR(20) not null)"""
    # 執行 SQL 指令
    cursor.execute(sql)
    
    sql = "INSERT INTO stu VALUES (104001, 'Claire', 'B342222', '1245667')"
    # 執行 SQL 指令
    cursor.execute(sql)
    
    sql = "INSERT INTO stu VALUES (104002, 'John', 'J224122', '222455')"
    # 執行 SQL 指令
    cursor.execute(sql)
    #--------------------------------------------------------------------------------
    
    # 創建成績表
    sql = """CREATE TABLE score(
            stuId INTEGER not null,
            sem VARCHAR(50) not null,
            sub VARCHAR(20) not null,
            score INT not null)"""
    # 執行 SQL 指令
    cursor.execute(sql)
    
    sql = "INSERT INTO score VALUES (104001, '1041', 'CH', 95)"
    # 執行 SQL 指令
    cursor.execute(sql)
    
    sql = "INSERT INTO score VALUES (104001, '1041', 'EN', 83)"
    # 執行 SQL 指令
    cursor.execute(sql)
    
    sql = "INSERT INTO score VALUES (104002, '1041', 'CH', 65)"
    # 執行 SQL 指令
    cursor.execute(sql)
    
    sql = "INSERT INTO score VALUES (104002, '1041', 'EN', 96)"
    # 執行 SQL 指令
    cursor.execute(sql)
    
    #--------------------------------------------------------------------------------
    # 查詢成績
    sql = "SELECT stu.name, score.sem, score.sub, score.score FROM\
            stu, score WHERE stu.stuId = score.stuId"
    cursor.execute(sql)
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    #--------------------------------------------------------------------------------
    #刪除資料表與資料庫
#     cursor.execute('DROP TABLE IF EXISTS stu')
#     cursor.execute('DROP TABLE IF EXISTS score')
#     cursor.execute('DROP DATABASE IF EXISTS practice')
    
# 關閉 SQL 連線
connect_db.close()

('Claire', '1041', 'CH', 95)
('Claire', '1041', 'EN', 83)
('John', '1041', 'CH', 65)
('John', '1041', 'EN', 96)


## 修改學生成績

**學生基本資料表與成績表同上題，修改成績表中學號為`104001`，學期為`1041`，科目為`EN`的成績，由83改成89，使用`UPDATE SET WHERE`修改成績**

In [7]:
import pymysql

try:
    connect_db = pymysql.connect(host="localhost", user="root", password="", 
                                 database="practice", charset='utf8' )
    print('連接成功')
    
except pymysql.Error as e:
    print('連接失敗' + str(e))

連接成功


In [8]:
with connect_db.cursor() as cursor:
    # 查詢成績
    sql = "SELECT stu.name, score.sem, score.sub, score.score FROM\
            stu, score WHERE stu.stuId = score.stuId"
    cursor.execute(sql)
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    # 修改成績
    sql = "UPDATE score SET score=89 WHERE stuId=104001 and sem='1041' and sub='EN'"
    # 執行 SQL 指令
    cursor.execute(sql)
    
    #--------------------------------------------------------------------------------
    # 查詢成績
    sql = "SELECT stu.name, score.sem, score.sub, score.score FROM\
            stu, score WHERE stu.stuId = score.stuId"
    cursor.execute(sql)
    rows = cursor.fetchall()
    for row in rows:
        print(row)
    
    #--------------------------------------------------------------------------------
    #刪除資料表與資料庫
#     cursor.execute('DROP TABLE IF EXISTS stu')
#     cursor.execute('DROP TABLE IF EXISTS score')
#     cursor.execute('DROP DATABASE IF EXISTS practice')
    
# 關閉 SQL 連線
connect_db.close()